name: Check files in .eslintignore

on:
  push:

env:
  PYTHON_VERSION: 3.9

jobs:
  eslintignore:
    name: "Check .eslintignore"
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python -m pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run script
        run: python __main__.py ${{ secrets.GITHUB_TOKEN }}
